api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    collection:
        pagination:
            client_enabled: false
            items_per_page: 20
            page_parameter_name: pagina
            client_items_per_page: true
            maximum_items_per_page: 30

#framework:
#    serializer: { enable_annotations: true }